sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t sipp11/docker-armv7-netatalk .
# test image
- docker run sipp11/docker-armv7-netatalk netatalk -v
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV NETATALK_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag sipp11/docker-armv7-netatalk sipp11/docker-armv7-netatalk:$TAG
    docker push sipp11/docker-armv7-netatalk:$TAG
    docker push sipp11/docker-armv7-netatalk
  fi
